name: Promote to Main

on:
  workflow_dispatch:

jobs:
  setup:
    uses: ./.github/workflows/reusable-setup.yml
  
  promote:
    needs: setup
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: release
      
      - name: Run tests
        run: npm test
      
      - name: Create PR to main
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "chore: promover release para main"
          title: "Promoção: Release → Main"
          body: |
            ## Promoção para Main
            
            Este PR promove as alterações da branch `release` para a branch `main`.
            
            Após a aprovação e merge deste PR, uma nova versão será publicada automaticamente.
          branch: promote-release-to-main
          base: main
          labels: |
            automated-pr
            release