name: Setup Environment

on:
  workflow_call:
    inputs:
      node-version:
        required: false
        default: '20.x'
        type: string

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ inputs.node-version }}
          cache: 'npm'
          
      - name: Install dependencies
        run: npm ci 